### PR TITLE
Added new query for multisite project

### PR DESCRIPTION
**Pull request by zaferkaymak**
When Navigating between sites, it was not rendering css of active web site. I added new query and it is working now.

### CODE REVIEW

**Comment by boutell** [comment]
Spinning up the site all over again every time the next request happens to be for another site is not the right answer, but it is a clue.

**Comment by boutell** [comment]
Is it possible this is just a caching issue in development? What do your URLs look like when you go between sites?

**Comment by zaferkaymak** [comment]
site urls:
1. site: http://firstsite:3000/
2. site: http://secondsite:3000/

**Comment by boutell** [comment]
This is going to leak ports and other resources a lot and be quite slow, but it shows there's some issue with the context switching.

Or... hmm.

Are you saying when you do this (without your patch):

1. Access first
2. Access second
3. Access first

You get no styles at all?

**Comment by boutell** [comment]
I'm closing it because this is not the right implementation, but that doesn't mean we're not interested in solving the underlying issue.

**Comment by zaferkaymak** [comment]
Yes I don't get no styles at all this process.

**Comment by boutell** [comment]
I used the project you provided and made two sites and was still unable to reproduce this issue.

**Pull request closed without merging**
